Базовая стилизация
htmlacademy-htmlcss/1800797-device-33 pull request #5
Opened 2022-02-22 19:44 UTC by Kirill-meta

2022-02-22 21:31 UTC, vlad-donchenko requested changes

2022-02-22 21:31 UTC, vlad-donchenko commented on catalog.html
> +              <button class="footer-navigation-link" type="button">Доставка</button>
Это тоже ссылка (эта ссылка должна вести на страницу доставки, но так нет такой страницы можно просто ссылку)

2022-02-22 21:31 UTC, vlad-donchenko commented on catalog.html
>            <ul class="footer-navigation-list>">
раньше говорил что это тот же список что и в header (navigation-list)  классы его дочерних элементов тоже сохраняем, а чтобы перекрасить цвет пунктов просто допиши к .navigation-list .navigation-list--white - так понятно что этот класс отвечает за цвет меню

2022-02-22 21:31 UTC, vlad-donchenko commented on index.html
> +        <a class="button-yellow" href="#">Подробнее</a>
Когда делаешь кнопку давай класс всегда .button - и выноси туда шрифты, и бокс дисплея если нужно и сброс стилей как правило это `text-decoration: none` - так как ссылки очень часто выглядят как кнопки, и `cursor: pointer` - так как у кнопок по-умолчанию `default`, а button-yellow - больше подходит к модификации кнопок, например у нас есть две кнопки в проекте желтая и красная, то ты просто бы дописал .button.button--yellow и .button.button--red - в доп классах (.button--red и .button--yellow)  - задал бы цвет! Задача очень проста вынести общие стили в класс а уникальные дописать через доп. кллас

2022-02-22 21:39 UTC, vlad-donchenko commented on styles/styles.css
> +
отформатируй css - не должно быть разных отступов, код должен быть однообразный и внутриблоков не должно быть отступов (это не ошибка, и на самом деле можно, работать будет, но просто это не красиво)
```
.class {
....
}
```

2022-02-22 21:39 UTC, vlad-donchenko commented on styles/styles.css
> +    font-style: "Raleway";
Нет такого значения ля свойства font-style! Возможно перепутал с` font-fammily`

2022-02-22 21:39 UTC, vlad-donchenko commented on styles/styles.css
> +    font-style: "Raleway";
нет смысла писать для текства шрифт он будет наследовать от родителя, просто укажи` font-family` для `body`

2022-02-22 21:39 UTC, vlad-donchenko commented on styles/styles.css
> +    color: #000000;
цвета неплохо выносит в переменные https://developer.mozilla.org/ru/docs/Web/CSS/Using_CSS_custom_properties

2022-03-02 12:27 UTC, Zotova2008 commented on index.html
>        <nav class="navigation">
1. На index.html Ссылка ведущая на текущую страницу пишется без атрибута href
```
<a class="navigation-logo">
  <img class="logo" src="images/header/logo.svg" width="145" height="36" alt="Логотип Девайс">
</a>
```

2. На catalog.html
```
<a class="navigation-logo" href="index.html">
  <img class="logo" src="images/header/logo.svg" width="145" height="36" alt="Логотип Девайс">
</a>
```

2022-03-02 12:27 UTC, Zotova2008 commented on index.html
> +              <button class="navigation-search" type="submit">Найти</button>
У разных элементов не должно быть одинакового класса. Форме так же лучше задать класс.
```
<form class="navigation-search" action="https://echo.htmlacademy.ru/" method="get">
  <label>
    <input class="navigation-search-input" type="search" name="search" placeholder="Текст поиска">
  </label>
  <button class="navigation-search-submit" type="submit">Найти</button>
</form>
```

2022-03-02 12:27 UTC, Zotova2008 commented on index.html
> +        <button class="button" type="button">Каталог товаров
Кнопка "Каталог товаров" (я бы ее сделала ссылкой, при не работающем script каталог можно было бы открыть на другой странице - и этой ссылке лучше задать другой класс, так как это не похоже на кнопку) и сам список товаров лучше обвернуть в div, что бы относительно него можно было бы позиционировать плашку с товарами.
Сам список товаров лучше разбить на 3 списка, во-первых тебе будет их не стилизовать по макету, а во-вторых это разные группы товаров. Либо сделать внутри списка 3 списка.
```
 <ul class="submenu-list">
  <li class="submenu-item">
    <a class="submenu-link" href="">Вирутальная реальность</a>       
    <a class="submenu-link" href="">Фитнесс браслеты</a>
    <a class="submenu-link" href="">Квадрокоптер</a>       
  </li>
  <li class="submenu-item">
    <a class="submenu-link" href="">Моноподы для селфи</a>
    <a class="submenu-link" href="">Умные часы</a>
  </li>
  <li class="submenu-item">
    <a class="submenu-link" href="">Экшн Камеры</a>       
  </li>
</ul>
```

2022-03-02 12:27 UTC, Zotova2008 commented on index.html
>          <ul class="navigation-list">
Меню: Доставка, Гарантия, Контакты. Это уже другое меню, другие характеристики текста, другая сетка. Лучше прописать другие классы, которые будут отличаться от меню, которое выше (войти-корзина)

2022-03-02 12:27 UTC, Zotova2008 commented on index.html
>          <button class="slider-button button-next" type="button">
Блок Слайдер. Его лучше перенести в header, что бы можно было нормально стилизовать желтую плашку, и сверстать нужно все слайды, не только тот который виден в макете (все слайды можно посмотреть в стайлгайде). Каждый слайд нужно обвернуть в обвертку.
```
<section class="slider">
  <h2 class="visually-hidden">Слайдер</h2>
  <div class="slider-wrapper">      
  
  Слайд у тебя разбит на две половинке. В левой картинка и стрелки, в правой текст. Поэтому каждую колонку нужно обвернуть в div 
  
  <div class="slider-item">
    
    Все контентные картинки лучше оборачивать в div, что бы на нем прописывать нужные размеры.
    
    <div class="slider-img">
       <img class="slider-photo" src="images/index/slider-1.png" width="540" height="640" alt="Фотография Квадракоптера">
     </div>
     
     Оборачиваем стрелочки для позиционирования.
     
     <div class="slider-arrows"
       <button class="slider-button button-prev" type="button">
          <span class="visually-hidden">Предыдущее фото</span>
        </button>
        <button class="slider-button button-next" type="button">
          <span class="visually-hidden">Следующее фото</span>
        </button>
     </div>
  </div>
  
  <div class="slider-content">
     <span class="slider-number">01</span>
     
     Дальше идет текст в виде заголовка, пропишем соответствующий класс (убераем тег br)
     
     <p class="device-upper-case slider-title">Порхает как бабочка, жалит как пчела!</p>
     
     Дальше идет описание, пропишем соответствующий класс (убераем тег br)
     
     <p class="slider-description">Этот обычный, на первый взгляд, квадрокоптер оснащен мощным лазером, замаскированным под стандартную камеру.</p>     
     
     Далее контент опять разделяется на две части. В одной части кнопка "Подробнее" и характеристики, а в другой пагинация
     
     <div class="silder-content-wrapper">
       <div class="slider-feature">
         <a class="button button-yellow" href="#">Подробнее</a>
         <table class="slider-table">
          <tr class="table-row">
            <td class="table-upper-case">800 м</td>
            <td class="table-upper-case">50 м</td>
          </tr>
          <tr class="table-row">
            <td class="table-lower-case">Далность полета</td>
            <td class="table-lower-case">Радиус поражения</td>
          </tr>
        </table>
       </div>
        
        <ol class="slider-pagination">
          <li class="slider-pagination-item>">
            <button class="slider-pagination-button slider-pagination-button-current" type="button">
              <span class="visually-hidden">1 слайд</span>
            </button>
          </li>
          <li class="slider-pagination-item>">
            <button class="slider-pagination-button" type="button">
              <span class="visually-hidden">2 слайд</span>
            </button>
          </li>
          <li class="slider-pagination-item>">
            <button class="slider-pagination-button" type="button">
              <span class="visually-hidden">3 слайд</span>
            </button>
          </li>
        </ol>
      </div>
  </div>
  <div class="slider-wrapper">...2 слайд...</div>
  <div class="slider-wrapper">...3 слайд...</div>
</section>
```

2022-03-02 12:27 UTC, Zotova2008 commented on index.html
>          <h2 class="visually-hidden">Список услуг</h2>
Блок с товарами. Картинку нужно обвернуть в div на котором у тебя будет желтый цвет, а внутри уже сама картинка. Атрибут href пустым не оставляем, обязательно прописываем #
```
<li class="product-item">
  <a class="product-link" href="#">
    <div class="product-img">
      <img class="product-image" src="images/index/virtual-reallity.svg" width="97" height="55" alt="Очки вирутальной реальности">
    </div>
    <span class="product-name">Виртульная реальность</span>
  </a>
</li>
```

2022-03-02 12:27 UTC, Zotova2008 commented on index.html
>          <ul class="services-list">
Блок с вкладками это уже другой крупный блок, нужно обвернуть в section
Кнопка "Доставка" - это выбранная кнопка, а не просто другого цвета.
```
<li class="services-item>">
  <button class="button button-current" type="button">Доставка</button>
</li>
```

Далее у нас идет блог с описанием вкладок, его нужно обвернуть в div и сверстать все блоки (можно посмотреть в стайлгайде) http://joxi.ru/Q2K8okvtg4yx6A.

У каждого блока своя иконочка, поэтому на каждый блок нужно повесить доп класс

```
<div class="services-description">
  <div class="services-description-item services-description-item-delivery">
    <h3 class="device-upper-case">Доставка</h3>
    <p class="services-delivery-lower-case">Мы с удовольствием доставим ваш товар прямо к вашему подъезду совершенно бесплатно! Ведь мы неплохо заработаем, поднимая его на ваш этаж.</p>
  </div>
  
  <div class="services-description-item services-description-item-garanty">...</div>
  <div class="services-description-item services-description-item-credit">...</div>
</div>
```

2022-03-02 12:27 UTC, Zotova2008 commented on index.html
>            <img class="delivery-info" src="images/index/i.svg" width="2" height="12" alt="значок информации">
"Значок информации" и "Иконка грузовика" это у нас будут псевдоэлементы, это не контентные изображение, т.е. сделаем мы их через css. 
```
<div class="delivery">
  <a class="delivery-link" href="#">Доставим редкий товар под заказ</a>
</div>
```
Эта ссылка должна открывать модальное окно

2022-03-02 12:27 UTC, Zotova2008 commented on index.html
>        <section class="about">
Блоки "О нас" и "Контакты" нужно обвернуть в один div, для сетки

2022-03-02 12:27 UTC, Zotova2008 commented on index.html
> +          <button class="button-index" type="submit">Подписаться</button>
Кнопка "Подписаться". Нужно прописать другой класс
`<button class="subcribe-submit" type="submit">Подписаться</button>`

2022-03-02 12:27 UTC, Zotova2008 commented on index.html
>            <input type="checkbox" name="subscribe" id="subscribe-field" checked>
Галочка у текста "Это бесплатно" это обычная фоновая картинка. input чекбокса убрать. Саму галочку заменить label на span или p

2022-03-02 12:27 UTC, Zotova2008 commented on index.html
>        </main>
Логотип "Device" в footer обвернуть в ссылку, как и в шапке.

2022-03-02 12:27 UTC, Zotova2008 commented on index.html
>            <ul class="footer-navigation-list>">
```
<ul class="footer-navigation-list>">
  <li class="footer-navigation-item">
    <a class="footer-navigation-white" href="#">Доставка</a>
  </li>
  <li class="footer-navigation-item">
    <a class="footer-navigation-white" href="#">Гарантия</a>
  </li>
 <li class="footer-navigation-item">
    <a class="footer-navigation-white" href="#">Контакты</a>
  </li>
</ul> 
```
Меню в футере. У ссылок убери класс button. В атрибутах href проставь #

2022-03-02 12:27 UTC, Zotova2008 commented on index.html
Меню и соц иконки обверни в div.
Телефон и логотип html обвернуть в div

2022-03-02 12:27 UTC, Zotova2008 commented on index.html
> +            <a class="footer-contacts-address-text" href="tel:88128121212">Тел.: +7 (812) 812-12-12</a>
Ссылку-телефон не нужно оборачивать в address

2022-03-02 12:27 UTC, Zotova2008 commented on catalog.html
>            <form action="https://echo.htmlacademy.ru/" method="get">
Форму поиска на странице каталога сделать так же как на главной странице

Во всех ссылках, если в проекте нет такой страницы прописать в атрибуте href #

2022-03-02 12:27 UTC, Zotova2008 commented on catalog.html
> +          <button class="button" type="button">Каталог товаров
На странице каталога Каталог товаров и меню "Доставка, гарантия, контакты" сделать так же как на главной странице

2022-03-02 12:27 UTC, Zotova2008 commented on catalog.html
> +                <a class="breadcrumbs-link inner-lower-case" href="#">Каталог товаров</a>
У Ссылки на страницу "Каталог товаров" в хлебных крошках удалить атрибут href

2022-03-02 12:27 UTC, Zotova2008 commented on catalog.html
>          <section class="catalog-products">
```
<!-- На весь section catalog-products делаем серый фон -->

    <section class="catalog-products">
      <div class="catalog-products-form">
        <h2 class="catalog-title">Фильтр:</h2>
        <form class="catalog-filter" action="https://echo.htmlacademy.ru/" method="get">

          <fieldset class="catalog-filter-group">Блок стоимость</fieldset>

          <fieldset class="catalog-filter-group">
            <legend class="catalog-filter-title">Цвет</legend>
            <ul class="catalog-filter-list">
              ...
            </ul>
          </fieldset>
          <fieldset class="catalog-filter-group">
            <legend class="catalog-filter-title">Bluetooth</legend>
            <ul class="catalog-filter-list">
              ...
            </ul>
          </fieldset>
          
          <!-- На кнопку "Показать" вешаем доп класс -->
         
          <button class="button button-yellow catalog-submit" type="submit">Показать</button>
      
        </form>
      </div>

      <div class="catalog-sorting">
        <h3 class="catalog-title">Сортировка:</h3>
        <select class="select-control" aria-label="Сортировка">
          <option value="popular">Популярное</option>
        
          <!-- Добавляем еще пару пунктов -->
        
          <option value="expensive">Дорогие</option>
        </select>

        <!-- Оборачиваем стрелочки в div и это не кнопки, а ссылки -->
       
        <div class="catalog-sorting-buttons">
          <a class="catalog-sorting-up" href="#">
            <span class="visually-hidden">кнопка вверх</span>
          </a>
          <a class="catalog-sorting-down" href="#">
            <span class="visually-hidden">кнопка вниз</span>
          </a>
        </div>
      </div>

      <div class="catalog-result">
        <ul class="product-list">
          <li class="product-item">
          
            <!-- Картинка и название должна быть каждая в своей ссылке -->
          
            <a class="product-link product-link-img">
              <img class="product-img" src="images/catalog/selfi-stick.jpg" width="360" height="380" alt="Любительская селфи-палка">
            </a>
           
            <!-- Оборачиваем название и цену в div для сетки -->
           
            <div class="product-description">
              <a class="product-link catalog-filter-title">
                <h3 class="product-name">Любительская селфи-палка</h3>
              </a>
            
              <!-- Цену делаем через span -->
            
              <span class="product-price">500 Р</span>
            </div>
            <div class="product-detail">
            
              <!-- Кнопка "Подробнее" это ссылка, обвернем ее в div, что бы сделать серый фон на всей карточке-->
            
              <a class="button button-yellow" href="#">Подробнее</a>
            </div>
          </li>
          ...
        </ul>

        <!-- Кнопка "Загрузить еще" это ссылка -->
      
        <a class="product-more catalog-title" href="#">Загрузить ещё</a>

        <div class="pagination">

          <!-- Ссылки "Назад и Вперед" не должны входить в список страниц, это отдельные ссылки -->
       
          <a class="pagination-link-text pagination-prev" href="#">Назад</a>

          <ul class="pagination-list">
            <li class="pagination-item">
              <a class="pagination-link" href="#">1</a>
            </li>
            <li class="pagination-item">
              <a class="pagination-link" href="#">2</a>
            </li>
            <li class="pagination-item">
              <a class="pagination-link" href="#">3</a>
            </li>
            <li class="pagination-item">
              <a class="pagination-link" href="#">...</a>
            </li>
            <li class="pagination-item">
              <a class="pagination-link" href="#">15</a>
            </li>
          </ul>

          <a class="pagination-link-text pagination-next" href="#">Вперёд</a>
        </div>
      </div>
</section>
```

2022-03-02 12:27 UTC, Zotova2008 commented on catalog.html
>        <footer class="page-footer">
Футер на странице каталога делаем аналогично главной странице

2022-03-02 12:27 UTC, Zotova2008 commented on index.html
> +        <button class="button button-yellow" type="button">Наришите нам</button>
`<button class="button button-yellow" type="button">Наришите нам</button>`  Текст "Напишите нам" и это не кнопка, а ссылка
`<a class="button button-yellow" href="#">Напишите нам</a>`

2022-03-02 12:27 UTC, Zotova2008 commented on styles/styles.css
> +    src: url("fonts/raleway/raleway-800.woff2") format("woff2");
Не правильно прописан путь до шрифта. В css все пути начинаются с двух точек
`src: url("../fonts/raleway/raleway-800.woff2") format("woff2");`

2022-03-02 12:27 UTC, Zotova2008 commented on styles/styles.css
> +    font-family: "Rubik", sans-serif;
В body `font-family` должен быть прописан и альтернативный шрифт, его можно выбрать https://www.cssfontstack.com/
Например
`font-family: "Rubik", "Arial", sans-serif;`
Аналогично и в других элементах

2022-03-02 12:27 UTC, Zotova2008 commented on styles/styles.css
> +.button {
`.button` пропиши border: none, background: none.
`.button-yellow` у тебя кнопка становится желтой только при наведении, и не вся, а только полосочка.
Подсказка: полоску сделать через псевдоэлемент

2022-03-02 12:27 UTC, Zotova2008 commented on styles/styles.css
> +.button-dark-yellow {
`.button-dark-yellow` нужно переименовать в `.button-current` и прописать только те свойства, которые различаются. Шрифт, размер уже прописаны в классе button дублировать их не нужно
Аналогично и в других элементах

2022-03-02 12:27 UTC, Zotova2008 commented on styles/styles.css
> +
Размеры шрифтов, цвет текста и т.д. сейчас проверять не буду, проверю на стадии  pixel perfect

2022-03-02 12:27 UTC, Zotova2008 commented on styles/styles.css
> +.page-header{
Фон в шапке и в блоке с вкладками  делается через градиент.

2022-03-02 12:27 UTC, Zotova2008 commented on styles/styles.css
> +.main-index {
не нужно на main-index прописывать белый фон. И не нужно на каждой странице писать разный класс для `<main>`. Пропиши на каждой странице `<main class="main">`

2022-03-02 12:27 UTC, Zotova2008 commented on styles/styles.css
> +.delivery-track {
Цвет должен быть прописан одинаково, либо заглавными буквами, либо строчными. Выбери что-то одно
```
.delivery-track {
    background-color:#FFE17F;

}

.delivery-info {
    background-color: #dcdcdc 50%;
}
```
и что ты имел ввиду под 50%? `background-color: #dcdcdc 50%;` Прозрачность? Цвет с прозрачностью задается через rgba

2022-03-02 12:35 UTC, Zotova2008 commented on styles/styles.css
> +
Так же настоятельно рекомендую прописать перед body 
```
html {
  box-sizing: border-box;
}

*,
*::before,
*::after {
  box-sizing: inherit;
}

img {
  max-width: 100%;
  height: auto;

  object-fit: cover;
  object-position: center;
}
```
Это значительно облегчит тебе жизнь с подгонкой размеров элементов и картинок

Так же всем ссылкам по их классам нужно прописать display block, inline-block или flex в зависимости от ситуации в противном случае ссылки не будут воспринимать размеры и отступы.

Картинка по их классам или от класса родителя прописать display block что бы избавиться от отступа который появляется у картинок, еще один из способов обнуление размера шрифта и line-height, но это старый способ, лучше block

2022-03-04 10:12 UTC, Zotova2008 commented on catalog.html
> +          <a class="button" href="">Каталог товаров
Ссылку "Каталог товаров" и  список товаров обвернуть в div

2022-03-04 10:12 UTC, Zotova2008 commented on catalog.html
> +          <ul class="navigation-user">
У списков меню user и list нужно все li в одинаковые классы прописать, такие же как в первом li http://joxi.ru/D2PMoNvtWpyQlA

2022-03-04 10:12 UTC, Zotova2008 commented on index.html
> +        <div class="slider-wrapper">
http://joxi.ru/8Angn1jHKj4Bjr каждый слайд нужно обвернуть в div.

2022-03-04 10:12 UTC, Zotova2008 commented on index.html
> +          <div class="slider-img">
Не много поменяем верстку в блоке слайдер.
1. Цифры 01, 02, 03 это нужно сделать через свойство counter - это автоматический счетчик.
2. Поменяем чуток структуру. У нас же стрелочки и буллиты должны быть одни на весь слайдер, меняется только контент и картинка.
`div cо стрелками` `div с буллитами и кнопкой подробнее` дальше идет `div c тремя слайдами`

2022-03-04 10:12 UTC, Zotova2008 commented on index.html
> +              <li class="slider-pagination-item>">
Буллиты - это у нас не 1 фото, 2 фото, 3 фото. А 1 слайд, 2 слайд, 2 слайд

2022-03-04 10:12 UTC, Zotova2008 commented on index.html
> +            <img class="slider-photo" src="images/header/slider-2.png" width="540" height="640" alt="Фотография Квадракоптера">
Фото браслета - нужно поменять alt и это уже другой слайд

2022-03-04 10:12 UTC, Zotova2008 commented on index.html
>              <button class="button button-yellow" type="button">Гарантия</button>
Не доделан блок с вкладками

Далее у нас идет блог с описанием вкладок, его нужно обвернуть в div и сверстать все блоки (можно посмотреть в стайлгайде) http://joxi.ru/Q2K8okvtg4yx6A.

У каждого блока своя иконочка, поэтому на каждый блок нужно повесить доп класс

```
<div class="services-description">
  <div class="services-description-item services-description-item-delivery">
    <h3 class="device-upper-case">Доставка</h3>
    <p class="services-delivery-lower-case">Мы с удовольствием доставим ваш товар прямо к вашему подъезду совершенно бесплатно! Ведь мы неплохо заработаем, поднимая его на ваш этаж.</p>
  </div>
  
  <div class="services-description-item services-description-item-garanty">...</div>
  <div class="services-description-item services-description-item-credit">...</div>
</div>
```

2022-03-04 10:12 UTC, Zotova2008 commented on index.html
>              <button class="button button-yellow" type="button">Гарантия</button>
Не переделан блок с ссылкой на модальное окно
"Значок информации" и "Иконка грузовика" это у нас будут псевдоэлементы, это не контентные изображение, т.е. сделаем мы их через css. 
```
<div class="delivery">
  <a class="delivery-link" href="#">Доставим редкий товар под заказ</a>
</div>
```
Эта ссылка должна открывать модальное окно

2022-03-04 10:12 UTC, Zotova2008 commented on index.html
>              <button class="button button-yellow" type="button">Гарантия</button>
Не сделано 
Блоки "О нас" и "Контакты" нужно обвернуть в один div, для сетки

2022-03-04 10:12 UTC, Zotova2008 commented on index.html
>              <button class="button button-yellow" type="button">Гарантия</button>
Не сделано 
Кнопка "Подписаться". Нужно прописать другой класс
`<button class="subcribe-submit" type="submit">Подписаться</button>`

Галочка у текста "Это бесплатно" это обычная фоновая картинка. input чекбокса убрать. Саму галочку заменить label на span или p

2022-03-04 10:12 UTC, Zotova2008 commented on index.html
>              <button class="button button-yellow" type="button">Гарантия</button>
Не сделано
Логотип "Device" в footer обвернуть в ссылку, как и в шапке.

2022-03-04 10:12 UTC, Zotova2008 commented on index.html
>              <button class="button button-yellow" type="button">Гарантия</button>
Не сделано
```
<ul class="footer-navigation-list>">
  <li class="footer-navigation-item">
    <a class="footer-navigation-white" href="#">Доставка</a>
  </li>
  <li class="footer-navigation-item">
    <a class="footer-navigation-white" href="#">Гарантия</a>
  </li>
 <li class="footer-navigation-item">
    <a class="footer-navigation-white" href="#">Контакты</a>
  </li>
</ul> 
```
Меню в футере. У ссылок убери класс button. В атрибутах href проставь #

2022-03-04 10:12 UTC, Zotova2008 commented on index.html
>              <button class="button button-yellow" type="button">Гарантия</button>
Не сделано
Меню и соц иконки обверни в div.
Телефон и логотип html обвернуть в div

2022-03-04 10:12 UTC, Zotova2008 commented on index.html
>              <button class="button button-yellow" type="button">Гарантия</button>
Не сделано 
Ссылку-телефон не нужно оборачивать в address

2022-03-04 10:12 UTC, Zotova2008 commented on index.html
> +        <a class="button" href="">Каталог товаров
Ссылке на каталог товаров убрать класс button, поставить другой класс. Прописать # в атрибуте href.
Аналогично сделать на обоих страницах

2022-03-04 10:12 UTC, Zotova2008 commented on index.html
> +        <div class="submenu">
Нужно обвернуть и ссылку на каталог товаров и submenu-list в один div
```
<div ...>
  <a ...>Каталог товаров</a>
  <ul class="submenu-list">...</ul>
</div>
```

Сделать аналогично и на другой странице

2022-03-04 10:12 UTC, Zotova2008 commented on index.html
>              <button class="button button-yellow" type="button">Гарантия</button>
Не сделано
```
<!-- На весь section catalog-products делаем серый фон -->

    <section class="catalog-products">
      <div class="catalog-products-form">
        <h2 class="catalog-title">Фильтр:</h2>
        <form class="catalog-filter" action="https://echo.htmlacademy.ru/" method="get">

          <fieldset class="catalog-filter-group">Блок стоимость</fieldset>

          <fieldset class="catalog-filter-group">
            <legend class="catalog-filter-title">Цвет</legend>
            <ul class="catalog-filter-list">
              ...
            </ul>
          </fieldset>
          <fieldset class="catalog-filter-group">
            <legend class="catalog-filter-title">Bluetooth</legend>
            <ul class="catalog-filter-list">
              ...
            </ul>
          </fieldset>
          
          <!-- На кнопку "Показать" вешаем доп класс -->
         
          <button class="button button-yellow catalog-submit" type="submit">Показать</button>
      
        </form>
      </div>

      <div class="catalog-sorting">
        <h3 class="catalog-title">Сортировка:</h3>
        <select class="select-control" aria-label="Сортировка">
          <option value="popular">Популярное</option>
        
          <!-- Добавляем еще пару пунктов -->
        
          <option value="expensive">Дорогие</option>
        </select>

        <!-- Оборачиваем стрелочки в div и это не кнопки, а ссылки -->
       
        <div class="catalog-sorting-buttons">
          <a class="catalog-sorting-up" href="#">
            <span class="visually-hidden">кнопка вверх</span>
          </a>
          <a class="catalog-sorting-down" href="#">
            <span class="visually-hidden">кнопка вниз</span>
          </a>
        </div>
      </div>

      <div class="catalog-result">
        <ul class="product-list">
          <li class="product-item">
          
            <!-- Картинка и название должна быть каждая в своей ссылке -->
          
            <a class="product-link product-link-img">
              <img class="product-img" src="images/catalog/selfi-stick.jpg" width="360" height="380" alt="Любительская селфи-палка">
            </a>
           
            <!-- Оборачиваем название и цену в div для сетки -->
           
            <div class="product-description">
              <a class="product-link catalog-filter-title">
                <h3 class="product-name">Любительская селфи-палка</h3>
              </a>
            
              <!-- Цену делаем через span -->
            
              <span class="product-price">500 Р</span>
            </div>
            <div class="product-detail">
            
              <!-- Кнопка "Подробнее" это ссылка, обвернем ее в div, что бы сделать серый фон на всей карточке-->
            
              <a class="button button-yellow" href="#">Подробнее</a>
            </div>
          </li>
          ...
        </ul>

        <!-- Кнопка "Загрузить еще" это ссылка -->
      
        <a class="product-more catalog-title" href="#">Загрузить ещё</a>

        <div class="pagination">

          <!-- Ссылки "Назад и Вперед" не должны входить в список страниц, это отдельные ссылки -->
       
          <a class="pagination-link-text pagination-prev" href="#">Назад</a>

          <ul class="pagination-list">
            <li class="pagination-item">
              <a class="pagination-link" href="#">1</a>
            </li>
            <li class="pagination-item">
              <a class="pagination-link" href="#">2</a>
            </li>
            <li class="pagination-item">
              <a class="pagination-link" href="#">3</a>
            </li>
            <li class="pagination-item">
              <a class="pagination-link" href="#">...</a>
            </li>
            <li class="pagination-item">
              <a class="pagination-link" href="#">15</a>
            </li>
          </ul>

          <a class="pagination-link-text pagination-next" href="#">Вперёд</a>
        </div>
      </div>
</section>
```

2022-03-04 10:12 UTC, Zotova2008 commented on index.html
>              <button class="button button-yellow" type="button">Гарантия</button>
Не сделано 
`<button class="button button-yellow" type="button">Наришите нам</button>`  Текст "Напишите нам" и это не кнопка, а ссылка
`<a class="button button-yellow" href="#">Напишите нам</a>`

2022-03-04 10:12 UTC, Zotova2008 commented on index.html
>          <ul class="services-list">
Не сделано
Не правильно прописан путь до шрифта. В css все пути начинаются с двух точек
`src: url("../fonts/raleway/raleway-800.woff2") format("woff2");`

2022-03-04 10:12 UTC, Zotova2008 commented on index.html
>              <button class="button button-yellow" type="button">Гарантия</button>
Не сделано
В body `font-family` должен быть прописан и альтернативный шрифт, его можно выбрать https://www.cssfontstack.com/
Например
`font-family: "Rubik", "Arial", sans-serif;`
Аналогично и в других элементах

2022-03-04 10:12 UTC, Zotova2008 commented on index.html
>              <button class="button button-yellow" type="button">Гарантия</button>
Не сделано
`.button` пропиши border: none, background: none.
`.button-yellow` у тебя кнопка становится желтой только при наведении, и не вся, а только полосочка.
Подсказка: полоску сделать через псевдоэлемент

2022-03-04 10:12 UTC, Zotova2008 commented on index.html
>              <button class="button button-yellow" type="button">Гарантия</button>
По макету желтый цвет начинается чуть ниже http://joxi.ru/vAWQoEjsR1nLxm
Поэтому нужно чуток подправить значение градиента - будет 3 цвета: белый, желтый, белый. Сделай по аналогии

2022-03-06 18:14 UTC, merged